name: Android CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Bước 1: Cấp quyền thực thi cho tệp gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Bước 2: Xây dựng APK
      - name: Build APK
        run: ./gradlew assembleRelease

      # Bước 3: Tải lên APK đã xây dựng
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk

      # Bước 4: Triển khai APK lên Google Play Store (ví dụ)
      - name: Deploy to Google Play
        uses: r0adkll/upload-google-play@v2
        with:
          serviceAccountJson: ${{ secrets.GOOGLE_PLAY_JSON }}
          packageName: com.example.myapp
          apkFiles: app/build/outputs/apk/release/app-release.apk
          track: internal
