name: Android CD

on:
  push:
    branches: [ "main" ]
  workflow_run:
    workflows: ["Android CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Bước 1: Setup JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      # Bước 2: Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Bước 3: Run ./gradlew assembleRelease
      - name: Build APK
        run: ./gradlew assembleRelease

      # Bước 4: Download APK from CI
      - name: Download APK from CI
        uses: actions/download-artifact@v2
        with:
          name: app-release
          path: app/build/outputs/apk/release

      # Bước 5: Deploy APK (có thể sử dụng hành động upload-google-play@v1)
      - name: Deploy to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.GOOGLE_PLAY_JSON }}
          packageName: com.example.myapp
          apkFiles: app/build/outputs/apk/release/app-release.apk
          track: internal
