name: Android CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate Firebase CLI
        run: firebase login:ci --no-localhost --interactive

      - name: Deploy to Firebase App Distribution
        run: firebase appdistribution:distribute ./app/build/outputs/apk/release/app-release.apk --token ${{ secrets.FIREBASE_TOKEN }}
